services:
  - type: web
    name: codecanvas
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: codecanvas-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: codecanvas-db
    plan: starter
    databaseName: codecanvas
    user: codecanvas
